name: return_app
description: "退货登记系统 - 多端同步数据管理"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  provider: ^6.1.2
  shared_preferences: ^2.3.3
  fl_chart: ^0.69.2
  intl: ^0.19.0
  pull_to_refresh_flutter3: ^2.0.2
  flutter_slidable: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
